source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'XCTest-Gherkin_Example' do
  pod "XCTest-Gherkin/Native", :path => "../"
  
  target 'XCTest-Gherkin_Tests'
  target 'XCTest-Gherkin_ExampleUITests'
end
