source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'XCTest-Gherkin_Example' do
  pod "XCTest-Gherkin/Native", :path => "../"
  
  target 'XCTest-Gherkin_Tests'
  target 'XCTest-Gherkin_ExampleUITests'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
