source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'XCTest-Gherkin_Example', :exclusive => true do
  pod "XCTest-Gherkin", :path => "../"
end

target 'XCTest-Gherkin_Tests', :exclusive => true do
  pod "XCTest-Gherkin", :path => "../"

  
end
