#!/usr/bin/env bash

# Lint from the root directory, so we lint the pod and the example project
pushd "${SRCROOT}/.."
  if [ -z "$TRAVIS" ]; then
    "${PODS_ROOT}/SwiftLint/swiftlint" --strict
  else
    "${PODS_ROOT}/SwiftLint/swiftlint"
  fi
  exit $?
popd

